### PR TITLE
(AB-1962930) Scaffold v2 documentation

### PR DESCRIPTION
**Pull request by michaeltlombardi**
# PR Summary

Prior to this change, the documentation for DSC v2 only included the overview.

This change:

- Extends the overview to include a high-level use case and the changes from DSC 1.1
- Copies the documentation from the conceptual docs for 1.1 for:
  - Getting Started (only including using `Invoke-DscResource` and linking to the Guest Configuration documentation)
  - Configurations (excluding the documentation for cross-node dependencies and reboot functionality, which are not supported with Guest Configuration)
  - Resources
  - Troubleshooting
- Includes a modified TOC

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
## Notes

Some working notes for this PR. Some of these need answers, some of these need to be converted into issues after discussion.

- [ ] Removed the pages for cross-node dependencies and rebooting as those scenarios are not supported
  in guest configuration.
- [ ] Need to clarify how data-driven configurations interact with guest configuration, given this [note](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration-custom#parameter-support-through-azure-resource-manager)
- [ ] Resource authoring is largely unchanged except for the special requirements for Get - should that be noted in these documents as well, or just link to guest configuration's documentation?
- [ ] Should the documentation for writing DSC Resources in C# be removed, or is it still valid for v2?
- [ ] Need to add a note to the documentation for MOF-based resources that this is supported but will
  not be in v3 and advise resource authors to convert to class-based resources.
- [ ] Are there any considerations for side-by-side versions of the same module in guest configuration?
- [ ] Are composite resources and/or composite configurations still valid?
- [ ] Does PSDscRunAsUser still work? Is it advised?
- [ ] Does the **DependsOn** meta-property still work? Is it advised?
- [ ] Need to rewrite the configuration documentation to be guest configuration specific since general
  configuration with the DSL is no longer supported.
- [ ] Kept the documentation for getting started on Windows, but it needs reworking for only calling `Invoke-DscResource`.
- [ ] Troubleshooting and debugging documentation needs to be reconfigured to only troubleshooting via
  `Invoke-DscResource`
  
CC @sdwheeler, @theJasonHelmick, @mgreenegit

**Comment by michaeltlombardi** [comment]
Invalid links will need to be addressed prior to merge, but for now I'm leaving them alone (as this is to the release branch `v2` and not `main`).

**Comment by sdwheeler** [comment]
Retrigger build

**Review by theJasonHelmick — APPROVED** [review]
This looks great!

**Pull request merged**
